# Configuración de email para envío de reportes
email_user = "tu_email@gmail.com"
email_password = "tu_password_de_aplicacion"

# Nota: Para Gmail, debes usar una contraseña de aplicación, no tu contraseña normal
# Para generar una contraseña de aplicación:
# 1. Ve a tu cuenta de Google
# 2. Seguridad > Verificación en dos pasos > Contraseñas de aplicación
# 3. Genera una nueva contraseña para esta aplicación 